name = "Ch4oS-Chilled"
version = "0.2.1"
description = "Minecraft 1.21.1 on NeoForge with LB Photo Realism Reload 128x, Bliss 2.1.2 and optional DERCODE 1.7."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44c83d1fa111d1e2a1f0f42c6aff111e6731d50b87934cadab72f5ee71194feb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
