name = "Ch4oS-Chilled"
version = "0.2.0"
description = "Minecraft 1.21.1 on NeoForge with LB Photo Realism Reload 128x and Bliss 2.1.2."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d379fc46e0cac92797dcf4094be6cfd6312ceea0133a195d830be8a72271d26a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
